# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 10
  start_block: 0
  contracts:
  - name: NonfungiblePositionManager
    address:
    - 0xC36442b4a4522E871399CD717aBDD847Ab11FE88
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
    - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
    - event: Collect(uint256 indexed tokenId, address recipient, uint256 amount0, uint256 amount1)
    - event: DecreaseLiquidity(uint256 indexed tokenId, uint128 liquidity, uint256 amount0, uint256 amount1)
    - event: IncreaseLiquidity(uint256 indexed tokenId, uint128 liquidity, uint256 amount0, uint256 amount1)
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
rollback_on_reorg: false
